import Foundation

/// Pure helpers for turning user text into a list of download URLs: parsing pasted lists /
/// `.txt` imports, and expanding numeric/alpha range patterns like `file[01-50].zip`.
///
/// Kept free of I/O and UI so it can be exhaustively unit-tested.
public enum URLBatch {

    /// The largest number of URLs one parse or pattern expansion may produce, guarding both
    /// combinatorial patterns and large pasted/imported batches.
    public static let expansionLimit = 10_000
    /// A single URL token cannot retain an arbitrarily large pasted value while the scanner waits
    /// for whitespace. This is intentionally far above practical URL limits.
    static let maximumTokenBytes = 64 * 1024
    /// The aggregate concrete strings generated by one operation are byte-bounded as well as
    /// count-bounded. A long common suffix therefore cannot amplify into hundreds of megabytes.
    static let maximumExpandedBytes = 10 * 1024 * 1024
    /// Enough for useful cartesian patterns while keeping adversarial singleton recursion finite.
    static let maximumPatternDepth = 64

    /// Parse free-form text (one URL per line, or whitespace-separated) into normalized,
    /// de-duplicated web/FTP URLs. Each token may itself be a range pattern, which is expanded.
    public static func parse(_ text: String) -> [URL] {
        parse(text, isCancelled: { false }) ?? []
    }

    /// Cancellation-aware parsing for debounced UI work.
    public static func parseCancellable(_ text: String) throws -> [URL] {
        guard let result = parse(text, isCancelled: {
            withUnsafeCurrentTask { $0?.isCancelled ?? false }
        }) else { throw CancellationError() }
        return result
    }

    private static func parse(_ text: String, isCancelled: () -> Bool) -> [URL]? {
        var seen = Set<String>()
        var result: [URL] = []
        var budget = ExpansionBudget()
        var token = ""
        var tokenBytes = 0
        var tokenIsOversized = false
        var bytesUntilCancellationCheck = 4_096

        func consumeToken() -> ExpansionStatus {
            defer {
                token.removeAll(keepingCapacity: true)
                tokenBytes = 0
                tokenIsOversized = false
            }
            guard !token.isEmpty, !tokenIsOversized else { return .completed }
            return forEachExpansion(in: token, budget: &budget, isCancelled: isCancelled) { concrete in
                guard let url = normalized(concrete), seen.insert(url.absoluteString).inserted else { return }
                result.append(url)
            }
        }

        guard !isCancelled() else { return nil }
        for scalar in text.unicodeScalars {
            let width = utf8Width(of: scalar)
            bytesUntilCancellationCheck -= width
            if bytesUntilCancellationCheck <= 0 {
                guard !isCancelled() else { return nil }
                bytesUntilCancellationCheck = 4_096
            }
            if CharacterSet.whitespacesAndNewlines.contains(scalar) {
                switch consumeToken() {
                case .completed: continue
                case .limitReached: return result
                case .cancelled: return nil
                }
            } else if !tokenIsOversized, width <= maximumTokenBytes - tokenBytes {
                token.unicodeScalars.append(scalar)
                tokenBytes += width
            } else {
                tokenIsOversized = true
            }
        }
        switch consumeToken() {
        case .completed: return isCancelled() ? nil : result
        case .limitReached: return result
        case .cancelled: return nil
        }
    }

    /// Expand a single token. If it contains range patterns, returns every concrete URL;
    /// otherwise returns the single normalized URL (or nothing if invalid).
    public static func expand(_ token: String) -> [URL] {
        guard token.utf8.count <= maximumTokenBytes else { return [] }
        let trimmed = token.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return [] }

        var result: [URL] = []
        var budget = ExpansionBudget()
        _ = forEachExpansion(in: trimmed, budget: &budget, isCancelled: { false }, visit: { concrete in
            if let url = normalized(concrete) { result.append(url) }
        })
        return result
    }

    /// Whether a token contains an expandable `[a-b]` range pattern.
    public static func containsPattern(_ token: String) -> Bool {
        token.utf8.count <= maximumTokenBytes && firstRange(in: token) != nil
    }

    // MARK: - Pattern expansion

    /// Visit concrete strings one at a time, with a hard recursion ceiling and no cartesian-product
    /// arrays. At most one candidate reaches normalization at a time.
    private static func forEachExpansion(
        in string: String,
        depth: Int = 0,
        budget: inout ExpansionBudget,
        isCancelled: () -> Bool,
        visit: (String) -> Void
    ) -> ExpansionStatus {
        guard !isCancelled() else { return .cancelled }
        guard let match = firstRange(in: string) else {
            guard budget.consume(string) else { return .limitReached }
            visit(string)
            return .completed
        }
        guard depth < maximumPatternDepth else { return .completed }

        let prefix = String(string[..<match.range.lowerBound])
        let suffix = String(string[match.range.upperBound...])
        for offset in 0..<match.values.count {
            let expanded = prefix + match.values.value(at: offset) + suffix
            switch forEachExpansion(
                in: expanded,
                depth: depth + 1,
                budget: &budget,
                isCancelled: isCancelled,
                visit: visit
            ) {
            case .completed: continue
            case .limitReached: return .limitReached
            case .cancelled: return .cancelled
            }
        }
        return .completed
    }

    private enum ExpansionStatus {
        case completed
        case limitReached
        case cancelled
    }

    private struct ExpansionBudget {
        var remainingCount = expansionLimit
        var remainingBytes = maximumExpandedBytes

        mutating func consume(_ string: String) -> Bool {
            let bytes = string.utf8.count
            guard remainingCount > 0, bytes <= remainingBytes else { return false }
            remainingCount -= 1
            remainingBytes -= bytes
            return true
        }
    }

    private struct RangeMatch {
        let range: Range<String.Index>
        let values: RangeValues
    }

    private enum RangeValues {
        case numeric(start: Int, count: Int, width: Int, padded: Bool)
        case alpha(start: UInt32, count: Int)

        var count: Int {
            switch self {
            case .numeric(_, let count, _, _), .alpha(_, let count): count
            }
        }

        func value(at offset: Int) -> String {
            switch self {
            case .numeric(let start, _, let width, let padded):
                let value = start + offset
                return padded ? String(format: "%0\(width)d", value) : String(value)
            case .alpha(let start, _):
                return Unicode.Scalar(start + UInt32(offset)).map(String.init) ?? ""
            }
        }
    }

    private static func firstRange(in string: String) -> RangeMatch? {
        guard let open = string.firstIndex(of: "["),
              let close = string[open...].firstIndex(of: "]"), close > open else { return nil }
        let inner = String(string[string.index(after: open)..<close])
        guard let values = rangeValues(in: inner) else { return nil }
        return RangeMatch(range: open..<string.index(after: close), values: values)
    }

    private static func rangeValues(in inner: String) -> RangeValues? {
        let parts = inner.split(separator: "-", maxSplits: 1, omittingEmptySubsequences: false)
        guard parts.count == 2 else { return nil }
        let lower = String(parts[0])
        let upper = String(parts[1])

        if let numeric = numericRange(lower, upper) {
            return numeric
        } else if let alpha = alphaRange(lower, upper) {
            return alpha
        }
        return nil
    }

    /// Describe `01-50` without allocating all values; formatting stays lazy during expansion.
    private static func numericRange(_ lower: String, _ upper: String) -> RangeValues? {
        guard lower.allSatisfy(\.isNumber), upper.allSatisfy(\.isNumber),
              let start = Int(lower), let end = Int(upper), start <= end else { return nil }
        let width = max(lower.count, upper.count)
        let padded = lower.first == "0" && lower.count > 1
        let (distance, overflow) = end.subtractingReportingOverflow(start)
        guard !overflow else { return nil }
        let count = distance >= expansionLimit ? expansionLimit : distance + 1
        return .numeric(start: start, count: count, width: width, padded: padded)
    }

    /// Expand `a-f` / `A-F` → consecutive single letters. Restricted to *same-case* ASCII
    /// letters so a cross-case pattern like `[A-z]` (whose scalar span includes `[ \ ] ^ _ \``)
    /// is rejected rather than expanded into punctuation-laced garbage URLs.
    private static func alphaRange(_ lower: String, _ upper: String) -> RangeValues? {
        guard lower.count == 1, upper.count == 1,
              let lo = lower.unicodeScalars.first, let hi = upper.unicodeScalars.first,
              lo.value <= hi.value else { return nil }
        let uppercase: ClosedRange<UInt32> = 65...90   // A...Z
        let lowercase: ClosedRange<UInt32> = 97...122  // a...z
        let sameCase = (uppercase.contains(lo.value) && uppercase.contains(hi.value))
            || (lowercase.contains(lo.value) && lowercase.contains(hi.value))
        guard sameCase else { return nil }
        return .alpha(start: lo.value, count: Int(hi.value - lo.value + 1))
    }

    // MARK: - Normalization

    /// Validate and normalize a single URL string, adding `https://` when no scheme is present.
    public static func normalized(_ raw: String) -> URL? {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        if let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "ftps"].contains(scheme) {
            return url
        }
        // Accept a bare host (we'll prepend https://) only if it actually looks like one — a
        // dotted name/IP or `localhost`. Otherwise a stray word ("notes", "todo") on its own
        // line would silently become a bogus download; the batch contract is to drop junk.
        if let url = URL(string: "https://\(trimmed)"), let host = url.host(),
           host == "localhost" || host.contains(".") {
            return url
        }
        return nil
    }

    /// A valid-string prefix whose UTF-8 representation never exceeds `maximumBytes`. If the byte
    /// boundary splits a multi-byte scalar, that partial scalar is omitted rather than replaced by
    /// U+FFFD (which itself would consume three bytes and could exceed the requested ceiling).
    public static func boundedInput(_ text: String, maximumUTF8Bytes maximumBytes: Int) -> String {
        guard maximumBytes > 0 else { return "" }
        let bytes = text.utf8
        guard bytes.count > maximumBytes else { return text }
        var end = bytes.index(bytes.startIndex, offsetBy: maximumBytes)
        while end != bytes.startIndex, bytes[end] & 0xC0 == 0x80 {
            end = bytes.index(before: end)
        }
        return String(bytes: bytes[..<end], encoding: .utf8) ?? ""
    }

    private static func utf8Width(of scalar: Unicode.Scalar) -> Int {
        switch scalar.value {
        case 0...0x7F: 1
        case 0x80...0x7FF: 2
        case 0x800...0xFFFF: 3
        default: 4
        }
    }
}
